config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :users, only: [] do
      resources :posts, only: [:index]
    end
    resources :posts, only: [:index] do
      resources :comments, only: [:index, :create]
  end
end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root 'users#index'
    resources :users, only: [:index, :show] do
      resources :posts, only: [:index, :show, :new, :create, :destroy] do
        post 'like', to: 'likes#create', on: :member, as:
        :user_post_likes
        resources :comments, only: [:create, :new, :destroy]
        resources :likes, only: [:create]

  end 
  get 'posts', to: 'posts#index', on: :member, as:
  :user_posts
  end 
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_save :update_posts_counter

  validates :title, length: { maximum: 250,
                              too_long: '250 characters is the maximum allowed' }

  validates(:comments_counter, :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 })

  def five_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def update_posts_counter
    author.update(post_counter: author.posts.count)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  before_action :set_user, only: %i[index show new create]
  before_action :set_post, only: [:show]
  before_action :inspect_user_and_ability

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:user, :comments, :likes).order(created_at: :desc)
  end

  def new
    @post = @user.posts.build
  end

  def create
    @post = @user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to user_post_path(@user, @post), notice: 'Post was succesfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def show
    @user = current_user
    @post = Post.includes(:author, :comments).find(params[:id])
    @comments = @post.comments
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    @post.update_posts_counter
    redirect_to user_posts_path(@post.author_id), notice: 'Post deleted successfully'
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end

  private

  def inspect_user_and_ability
    Rails.logger.debug("Current User: #{current_user.inspect}")
    Rails.logger.debug("Ability: #{current_ability.inspect}")
  end
end

app/controllers/users/api/posts_controller.rb
module Api
  class PostsController < ApplicationController
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:author, comments: [:user])

    render json: @posts
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<%= stylesheet_link_tag('posts_index') %>

<%= link_to "Create Post", new_user_post_path(@user),
class: 'button' %>

<%= render "application/user" %>
<div class="posts-container">
<% @user.posts.each do |post| %>
<div class="posts">
<div class= "post1">
  <h4 class= "title"> <%= link_to post.title, user_post_path(@user, post) %></h4><br>
  <p><%= post.text.split[0, 10].join(' ') %></p><br>

  <%= render "application/like" %>
  <div class="span">
    <span >Comments <%= post.comments_counter %> Likes <%= post.likes_counter%> </span>
  </div>
</div>

<div class="comments">
    <% if post.comments.any? %>
      <% post.comments.limit(5).each do |comment| %>
      <div class="comment">
        <span><%= comment.user.name%>: 
        <%= comment.text%> </span>
      </div>
    <% end %>

    <% else %>
      <p>No comments available!</p>
    <% end %>
</div>
</div>
<%end%>
<div class= "pagination-container">
  <button type="button">Pagination</button>
</div>
</div>
</div>

app/views/posts/new.html.erb
<%= form_with model: [@user, @post], url:
user_posts_path, method: :post do |form| %>
    <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div class="field">
        <%= form.label :text %>
        <%= form.text_area  :text %>
    </div>

    <div class="actions">
        <%= form.submit "Create Post" %>
    </div>
<% end %>

app/views/posts/show.html.erb
<%= stylesheet_link_tag('posts_show') %>

<div class="extended-posts">
  <div class="extended-post-header">
    <h4><%= @post.title %> by <%= @user&.name%></h4>
    <form action="/users/:user_id/posts/:post_id/likes" method="post">
      <input type="hidden" name="like[post_id]" value="<%= @post.id %>">
      <input type="submit" value="Like">
    </form>
    <span class="reaction-counter">Comments <%= @post.comments_counter %> Likes <%= @post.likes_counter%> </span>
  </div>
  <div class="post-text-extended">
    <p><%= @post.text%></p>
    <% if can?(:destroy, @post) %>
      <form action="<%= user_post_path(@user, @post) %>" method="post">
        <%= hidden_field_tag :_method, :delete %>
        <%= csrf_meta_tags %>
        <input type="submit" value="Delete Post" onclick="return confirm('Are you sure?');">
      </form>
    <% end %>
  </div>
 
  </div>

  <%= link_to "Add Comment", new_user_post_comment_path(@user, @post),
class: 'comment-button' %>

  <div class="comments">

    <% if @post.comments.any? %>
      <% @post.comments.each do |comment| %>
      <div class="comment">
        <span><%= comment.user&.name %>: <%= comment.text%> </span>
        <% if can?(:destroy, comment) %>
          <%= form_with(model: [@user, @post, comment], url: user_post_comment_path(@user, @post, comment), method: :delete) do |form| %>
          <%= form.hidden_field :_method, value: :delete %>
          <%= form.submit "Delete Comment", onclick: "return confirm('Are you sure?')" %>
        <% end %>
    <% end %>
      </div>
    <% end %>

    <% else %>
      <p>No comments available!</p>
    <% end %>
</div>